#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset

bspc config border_width         1.5
bspc config border_radius        12
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

_JAVA_AWT_WM_NONREPARENTING=1
#
# Autostart
#
# Set display from arandr saved script
# Bar
~/.config/polybar/launch.sh
# Notifications
dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
feh --bg-fill ~/Pictures/gruvbox_room.png
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
# picom -b &
picom --xrender-sync-fence &
# Network Applet
nm-applet &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh &

# Keyboard layout
setxkbmap -option grp:alt_shift_toggle fr,ara & 
#DISPLAY=:0 keyb &

# kill firewall applet
sleep 2 && pkill firewall-applet
